onlineshop/urls.py
from django.contrib import admin
from django.urls import path,include
from register import views
import product
from onlineshop import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/',include('product.urls')),
    path('register/',views.register_req,name="register"),
    path('login/',views.login_req,name="login"),
    path('home/',views.home_req,name="home"),
    path('logout/',views.logout_req,name="logout"),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from product import views
from onlineshop import settings
from django.conf.urls.static import static
my_app="product"

urlpatterns = [
    path('createp/',views.createproduct,name="createp"),
    path('readp/',views.readproduct,name="readp"),
    path('modifyp/<id>',views.modifyproduct,name="modifyp"),
    path('deletep/<id>',views.deleteproduct,name="deletep"),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models

# Create your models here.
class ProductItem(models.Model):
     item=models.CharField(max_length=30)
     def __str__(self):
         return self.item
     
class Productdb(models.Model):
    pname=models.CharField(max_length=30)
    pdesc=models.CharField(max_length=200)
    pprice=models.FloatField()
    pdiscount=models.FloatField()
    pimg=models.ImageField(upload_to='product/%y/%m/%d')
    item=models.ForeignKey(ProductItem,on_delete=models.CASCADE)
    
    

register/models.py
from django.db import models

# Create your models here.

product/forms.py
from django import forms
from product.models import Productdb
from django.core.files.storage import FileSystemStorage

class Productform(forms.ModelForm):
    class Meta:
        model = Productdb
        fields = '__all__'
    

register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUser(UserCreationForm):
    phone=forms.IntegerField(widget=forms.TextInput())
    class Meta:
        model = User
        fields=("username","email","phone","password1","password2")
    
    def save(self, commit=True):
        user=super(NewUser,self).save(commit=False)
        user.phone=self.cleaned_data['phone']
        if commit:
            user.save()
        return user
        

product/views.py
from django.shortcuts import render
from product.forms import Productform
from product.models import Productdb
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib import messages

# Create your views here.
def createproduct(request):
    #get the data
    if request.method=='POST':
        form = Productform(request.POST,request.FILES)
        if form.is_valid():
            user=form.save(commit=False)
            upload_image=request.FILES.get("pimg")   
            fs = FileSystemStorage()
            file =fs.save(upload_image.name,upload_image)
            user.pimg=file
            form.save()
            '''
            pname=request.POST.get("pname")   
            pdesc=request.POST.get("pdesc")   
            pprice=request.POST.get("pprice")   
            pdiscount=request.POST.get("pdiscount")   
            
            var = Productdb.objects.create(pname=pname,pdesc=pdesc,pprice=pprice,pdiscount=pdiscount,pimg=file)
            '''
            messages.success(request,"your product is created in the db")
    #post the data
    form = Productform()
    return render(request,"createpro.html",{'form':form})

def readproduct(request):
    var=Productdb.objects.all()
    return render(request,"readpro.html",{'form':var})

def modifyproduct(request,id):
    var=Productdb.objects.get(id=id)
    if request.method=='POST':
        form = Productform(request.POST,request.FILES,instance=var)
        if form.is_valid():
            print(form)
            user=form.save(commit=False)
            upload_image=request.FILES.get("pimage")
            print(upload_image)
            if upload_image!=None:
                fs = FileSystemStorage()
                file =fs.save(upload_image.name,upload_image)
                user.pimg=file
                form.save()
                messages.success(request,"your product is modify in the db")
            form.save()
            messages.success(request,"your product is modify in the db without image")
          
    return render(request,"modifypro.html",{'upd':var})

def deleteproduct(request,id):
    var=Productdb.objects.get(id=id)
    var.delete()
    messages.success(request,"your product is delete in the db")
    return HttpResponseRedirect('/product/readp/')
    

register/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from register.forms import NewUser
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
# Create your views here.
def register_req(request):
    if request.method=="POST":
        form = NewUser(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            messages.success(request,"registeration succcess")
        messages.error(request,"registeration unsucccessfull")
    form=NewUser
    return render(request,"register.html",{'register_form':form})

def login_req(request):
    if request.method=="POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username=form.cleaned_data.get("username")
            password=form.cleaned_data.get("password")
            user=authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect('/home/?success=1')
            else:
                messages.error(request,"invaild username and password")
        else:
            messages.error(request,"invaild username and password")
    form=AuthenticationForm
    return render(request,"login.html",{'login_form':form})
def home_req(request):
    return render(request,"home.html")
def logout_req(request):
    logout(request)
    return redirect("home")

product/templates/createpro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class=container align="center">
        {%for msg in messages%}
        <h3>{{msg}}</h3>
        {%endfor%}
        </div>
    <div class=container align="center">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit", value="createproduct">
            </form>
        </div>
</body>
</html>

product/templates/modifypro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class=container align="center">
        {%for msg in messages%}
        <h3>{{msg}}</h3>
        {%endfor%}
        </div>
    <div class=container align="center">
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token%}
<table>
<tr><th><label for="id_pname">Pname:</label></th><td><input type="text" name="pname" maxlength="30" required id="id_pname" value="{{upd.pname}}"></td></tr>
<tr><th><label for="id_pdesc">Pdesc:</label></th><td><input type="text" name="pdesc" maxlength="200" required id="id_pdesc" value="{{upd.pdesc}}"></td></tr>
<tr><th><label for="id_pprice">Pprice:</label></th><td><input type="number" name="pprice" step="any" required id="id_pprice" value="{{upd.pprice}}"></td></tr>
<tr><th><label for="id_pdiscount">Pdiscount:</label></th><td><input type="number" name="pdiscount" step="any" required id="id_pdiscount" value="{{upd.pdiscount}}"></td></tr>
<tr><th><label for="id_pimage">Pimgage:</label></th><td><input type="file" name="pimage" accept="image/*" id="id_pimage"></td></tr>
</table>
<br>
<br>
<input type="submit" value="UPDATE RECORD">
</form>
<label for="" >productimage:</label></th><td><img src="{{upd.pimg.url}}" alt="no img found" height="100" width="150">
<br><br>
<button><a href='/product/readp/'>LIST OF PRODUCTS</a></button></td>
</div>

</body>
</html>

product/templates/readpro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class=container align="center">
    {%for msg in messages%}
    <h3>{{msg}}</h3>
    {%endfor%}
    </div>
    
    <div class=container align="center">
    <table border="2">
        <th>productid</th>
        <th>productname</th>
        <th>productdesc</th>
        <th>productprice</th>
        <th>productdiscount</th>
        <th>productimage</th>
        <th>productmodify</th>
        <th>productdelete</th>

        {%for i in form%}
        <tr>
        <td>{{i.id}}</td>
        <td>{{i.pname}}</td>
        <td>{{i.pdesc}}</td>
        <td>{{i.pprice}}</td>
        <td>{{i.pdiscount}}</td>
        <td> <img src="{{i.pimg.url}}" alt="no img found" height="100" width="150"></td>
        <td> <a href='/product/modifyp/{{i.id}}'>MODIFY</a></td>
        <td> <a href='/product/deletep/{{i.id}}'>DELETE</a></td>
        </tr>
        {%endfor%}
        </table>   
    </div>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%for msg in messages%}
    <h4>{{msg}}</h4>
    {%endfor%}
    {%if user.is_authenticated%}
    <h1>HOMEPAGE</h1>
    <h2>welcome to {{user.username}}</h2>
    <a href="/logout/">Logout</a>
    {%else%}
    <h2>you are not logged in plz login</h2>
    <a href="/login/">Login</a>
    {%endif%}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%for msg in messages%}
    <h4>{{msg}}</h4>
    {%endfor%}
<form method="POST">
    {% csrf_token %}
    <h1>LOGIN PAGE</h1>
    {{login_form.as_p}}
    <input type="submit" value="LOGIN">
</form>
<p>if you not have any account,<a href="/register/"><h3>register</h3></a>instead </p>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
    div.container6 {
        height: 10em;
        display: flex;
        align-items: center;
        justify-content: center }
      div.container6 p {
        margin: 0 }
      </style>
</head>
<body >
    <div class="container6">
    {%for msg in messages%}
    <h4>{{msg}}</h4>
    {%endfor%}
<form method="POST">
    {% csrf_token %}
    <h1>REGISTER PAGE</h1>
    {{register_form.as_p}}
    <input type="submit" value="REGISTER">
</form>
<p>if you already have an account,<a href="/login/">login</a>instead </p>
</div>
</body>
</html>